package com.mindhubweb.salvo.model;

public enum  ShipType {
    MELONPULTA, HIELAGUISANTES, LANZAGUISANTES, CARRONIVERA, LANZAMAIZ, ZOMBIE_COMUN,ZOMBIE_LECTOR,ZOMBIE_BAILARIN,ZOMBIE_PLAYERO,ZOMBISTEIN

}
