package com.mindhubweb.salvo.model;

public enum  ShipType {
    MELONPULTA, HIELAGUISANTES, LANZAGUISANTES, CARRONIVERA, LANZAMAIZ, ZOMBIECOMUN, ZOMBIELECTOR, ZOMBIEBAILARIN, ZOMBIEPLAYERO,ZOMBISTEIN

}
